### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by vresetnikov** [worldline/learning-kotlin#95]
Hello, 

I would like to report a typo that I ran into while reading your documentation. 

Location: https://worldline.github.io/learning-kotlin/en/front-development/

Sentence in question: With KotlinJS, developers can create React, nodsjs, or vanilla JS Apps using Kotlin.

typo: nodsjs (should be node.js)

Thank you

**Comment by yostane** [comment]
Hello,
You're welcome!
Thanks a lot for the feedback. This has been fixed :)
Best regards,
